### ISSUE TITLE
Present summary of Gradle build warnings in Job Summary and PR comment

### ISSUE THREAD

**Issue by michael-arndt-gcx** [gradle/actions#317] opened 2024-07-31 08:59 UTC
During our build, gradle emits various warnings. Currently they are almost invisible, i.e. we need to look at the log of the workflow run.

Examples for warnings we currently get are:

Gradle deprecation warnings:

```
The Configuration.fileCollection(Spec) method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use Configuration.getIncoming().artifactView(Action) with a componentFilter instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.9/userguide/upgrading_version_8.html#deprecate_filtered_configuration_file_and_filecollection_methods
```

kotlin compiler warnings

```
w: Kapt currently doesn't support language version 2.0+. Falling back to 1.9.
```

I would like to have some way to collect these and make them visible in a PR. At least as report, preferably as PR comment.

**Comment by bigdaz** [comment] 2024-07-31 18:51
Thanks for the idea. Currently we don't have a mechanism to collect these warnings from Gradle, and we don't have any way to parse the GitHub Actions log output either. So I can't see an easy way to do this right now.

However, with the introduction of the [Problems API](https://docs.gradle.org/current/javadoc/org/gradle/api/problems/Problems.html) in Gradle we might have a mechanism to collect these warnings.

**Comment by bigdaz** [comment] 2024-07-31 18:54
Closing as duplicate of #30

**Closed** 2024-07-31 18:54 UTC
