### ISSUE TITLE
Dependabot PR

### ISSUE THREAD

**Issue by oletjens** [gradle/actions#137] opened 2024-04-09 20:11 UTC
I just got an automatic Dependabot PR on my Github action setup:
```
- uses: gradle/actions/setup-gradle@v3
+ uses: gradle/actions/setup-gradle@v321
```
Is this intentional?
Should I not stay on `v3` to always get the latest majorversion 3?

**Comment by hfhbd** [comment] 2024-04-09 20:22
Duplicate of https://github.com/gradle/actions/issues/130

**Comment by bigdaz** [comment] 2024-04-09 20:23
This is due to an oversight on my part, and some questionable behaviour by Dependabot. You can close and ignore that PR.
See #130 

When you say you "just got" this PR, can you see the timestamp when it was generated?
I'm hoping that this issue was limited to Dependabot runs during the 1hr window when the `v321` branch existed on the repository.

**Closed by bigdaz** 2024-04-09 20:23 UTC
Labels: duplicate

**Comment by oletjens** [comment] 2024-04-09 20:42
@bigdaz Sorry "just got" was not completely true. The PR was created by Dependabot around: 2024-04-08T18:29:39Z

**Comment by bigdaz** [comment] 2024-04-09 20:48
> @bigdaz Sorry "just got" was not completely true. The PR was created by Dependabot around: 2024-04-08T18:29:39Z

Thanks. That fits in the window of time when the `v321` branch existed. Apologies for the inconvenience.
