### ISSUE TITLE
setup-gradle is not able to use the configuration cache

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/actions#457] opened 2024-11-19 18:12 UTC
I am trying to get configuration cache to work with setup-gradle github action.. but it doesn't seem to be working.

Here is the reason that shows up every time:
Calculating task graph as configuration cache cannot be reused because file '../../../../../../src900954567/src/actions-runner/_work/messaging/messaging/settings.gradle.kts' has been removed.

We are using aws hosted github runners.

The relevant github action setup is as follows:
```
    - name: Setup Java
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        gradle-version: "wrapper"
        cache-read-only: false
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        cache-overwrite-existing: true
        add-job-summary-as-pr-comment: on-failure
        cache-cleanup: never
```

**Comment by bigdaz** [comment] 2024-12-09 15:40
Thanks for the report and apologies for the delayed reply. You are likely running into #21 which makes it tricky to get configuration-cache reuse working.

**Comment by NikolayMetchev** [comment] 2024-12-10 13:20
I did have an included settings build but removing it hasn't fixed the issue. I still get the same problem and I no longer have included builds.

**Comment by bigdaz** [comment] 2024-12-12 18:54
Yes `buildSrc` contains outputs that need to be present in order to benefit from config-cache reuse.

Closing as a duplicate of #21

**Closed by bigdaz** 2024-12-12 18:54 UTC
