### ISSUE TITLE
Post Cleanup uses gradle instead gradlew

### ISSUE THREAD

**Issue by hfhbd** [gradle/actions#158] opened 2024-04-11 09:11 UTC
The default GitHub runner have `gradle` preinstalled, but custom runner might not.

Output of custom runner without `gradle`, but JVM and `gradlew`:
```
Warning: Cache cleanup failed. Will continue. Error: Unable to locate executable file: gradle. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by bigdaz** [comment] 2024-04-11 14:02
Duplicate of #33.

I don't think we should rely on the wrapper from the project: this would mean supporting cache cleanup with many different Gradle versions. New Gradle versions cleanup HOME for all older versions, but not the other way around.

Instead we should install the latest Gradle if it's not on PATH, and use that.

**Closed by bigdaz** 2024-04-11 14:02 UTC
