### ISSUE TITLE
[setup-gradle action] Update PR Comment Instead of Posting New One for Each Commit

### ISSUE THREAD

**Issue by can019** [gradle/actions#369] opened 2024-09-09 14:46 UTC
## Current
In the current setup, the action posts a new PR comment for every commit. This results in multiple comments, one for each commit, which can clutter the pull request discussion.

![스크린샷 2024-09-09 오후 11 45 17](https://github.com/user-attachments/assets/c160cf63-d793-4b97-8caf-e7f1eb7a8289)

## Desired Behavior:
I would like the action to update an existing PR comment (if one exists) rather than posting a new one for each commit. If the comment already exists, it should be edited with the new information. Ideally, there would be only one comment per pull request, and this comment should get updated as more commits are pushed.

## Example Workflow:
When the first commit is pushed, the action creates a comment.
For subsequent commits, the action updates the same comment with the latest information.
The PR should only have one comment from the action, regardless of how many commits are made.
This would help keep the PR discussion cleaner and more manageable.

Thank you!

**Comment by bigdaz** [comment] 2024-09-09 15:50
Thanks! This is a duplicate of #176.
Feel free to add more context to that issue.

**Closed by bigdaz** 2024-09-09 15:50 UTC
