### ISSUE TITLE
Dependency submission fails with HttpError

### ISSUE THREAD

**Issue by glinero-king** [gradle/actions#190] opened 2024-04-19 08:34 UTC
In some cases only, after the dependency graph is generated using the action, the submission fails throwing an HttpError.

```
Found dependency graph files: /runner/_work/king_constants/king_constants/dependency-graph-reports/build-build.json
Error: Error: Dependency submission failed for dependency-graph-reports/build-build.json.
HttpError: An error occurred while processing your request. Please try again later.
```

The dependency graph is enabled and the workflow has read and write permissions on the repository, however I cannot find more detailed logs to look into the problem.

**Comment by bigdaz** [comment] 2024-04-19 14:08
Thanks for your report. This looks like a server-generated error: is it happening consistently?
Can you [re-run the workflow jobs with debug logging enabled](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#debugging-and-troubleshooting)?

**Comment by glinero-king** [comment] 2024-04-19 14:21
This action is part of a multi-step action we run and the error happens consistently. We have also created a separated workflow with this particular action isolated to make sure it still happens and run it with debug-logging enabled.
However the problem persists and the debug logs do not really shed much light...

The error points to something on the server when the HTTP request is done to push the dependency graph, but is so generic that is difficult to understand what is going on.

Adding a file with the output of the dependency graph submission.
[GitHubDependencyGraphRenderer-log.txt](https://github.com/gradle/actions/files/15041739/GitHubDependencyGraphRenderer-log.txt)

**Comment by bigdaz** [comment] 2024-04-19 16:26
@glinero-king I've pushed a change to the `main` branch that tries to preserve more of the error that we get from GitHub: are you able to try this out? You should see a stacktrace logged with the error message.

You'll need to temporarily switch from:
```
uses: gradle/actions/dependency-submission@v3
```
to
```
uses: gradle/actions/dependency-submission@main
```

If this helps, I can try to get a release published with this fix.

**Comment by bigdaz** [comment] 2024-04-19 16:41
You mention that failure happens "in some cases only". I wonder if the problem is in the generated dependency-graph file itself.

- Is there anything distinctive about the failing cases?

- Can you inspect the generated dependency graph files to compare? If you change to use `generate-and-upload` you'll see the graph as a workflow artifact: see [this example](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#usage-with-pull-requests-from-public-forked-repositories).

- Can you share the failing dependency-graph file?

**Comment by bigdaz** [comment] 2024-04-29 06:44
@glinero-king Without more information there isn't much we can do to address this issue. I'm going to close it for now. If you can provide more context then I'll be happy to re-open it.

The latest release of the action attempts to preserve more context around dependency-submission failures like this, so if you have more details to add that would be great.

**Closed by bigdaz** 2024-04-29 06:44 UTC

**Comment by glinero-king** [comment] 2024-04-29 08:37
Hi @bigdaz sorry for the radio silent but I've been disconnected for the past week.
We are testing using the main branch to try to see more information on the error log.
Regarding using generate-and-upload, I get an error because apparently the version of actions/upload-artifact is not compatible with Github Enterprise. I guess that is an action that is the submission action uses

**Comment by bigdaz** [comment] 2024-04-29 09:14
Yes, we recently updated to use the latest version of upload-artifact, which uses new backend infrastructure. Are you running the latest version of GHES?

**Comment by bigdaz** [comment] 2024-04-29 09:38
Do you really need to use dependency-submission in the “generate-and-upload” mode? If you can use generate-and-submit instead then the ‘upload-artifact’ api isn’t used.

**Comment by glinero-king** [comment] 2024-04-29 15:20
so we do not need to use the generate-and-upload mode.
What we do is just use the dependency-submission action to generate the dependency graph.
After using the @main branch, we got more logging but I still do not see much more information about the HTTP error

```
BUILD SUCCESSFUL in 15s
9 actionable tasks: 9 executed
Found dependency graph files: /runner/_work/king_constants/king_constants/dependency-graph-reports/build-build.json
Error: HttpError: Dependency submission failed for dependency-graph-reports/build-build.json.
An error occurred while processing your request. Please try again later.
HttpError: Dependency submission failed for dependency-graph-reports/build-build.json.
An error occurred while processing your request. Please try again later.
    at /runner/_work/_actions/gradle/actions/main/dist/dependency-submission/main/index.js:57939:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async submitDependencyGraphFile (/runner/_work/_actions/gradle/actions/main/dist/dependency-submission/main/index.js:144806:22)
    at async submitDependencyGraphs (/runner/_work/_actions/gradle/actions/main/dist/dependency-submission/main/index.js:144779:13)
    at async Object.complete (/runner/_work/_actions/gradle/actions/main/dist/dependency-submission/main/index.js:144723:17)
    at async run (/runner/_work/_actions/gradle/actions/main/dist/dependency-submission/main/index.js:144945:9)
Run ./gradlew sonar
Generating dependency graph into '/runner/_work/king_constants/king_constants/dependency-graph-reports/build-build-1.json'
Resolving dependency graph plugin 1.3.0 from plugin repository: https://plugins.gradle.org/m2
```

We can try going back to the v3 and test those steps

**Comment by bigdaz** [comment] 2024-04-29 20:17
Got it. It's a shame that the server doesn't provide any further details on the failure.
But I suspect the issue is with GHES not supporting dependency submission in the same way as github.com. 

I'd like to see the content of `/runner/_work/king_constants/king_constants/dependency-graph-reports/build-build.json` from the workflow run. Since you can't rely on `generate-and-upload` to do this, you'd need to retrieve it some other way that works on your GHES: perhaps `actions/upload-artifact@v3` would work.

You can then try to manually submit the dependency graph to the [Dependency Submission API](https://docs.github.com/en/enterprise-server@3.11/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28). The response should give you more details as to what's going wrong. eg maybe there's a proxy server preventing this request, or maybe your GHES doesn't support Dependency Submission.

**Comment by glinero-king** [comment] 2024-04-30 05:46
It is weird that only happens on certain repositories.

Here is an example of a gradle build (very simple) where we use to test new changes and it works perfectly.

```
BUILD SUCCESSFUL in 19s
1 actionable task: 1 executed
Found dependency graph files: /runner/_work/Platsec-Gradle-Sample/Platsec-Gradle-Sample/dependency-graph-reports/platform_security_scan-build.json
Notice: Submitted dependency-graph-reports/platform_security_scan-build.json: Dependency results for the repo have been successfully updated.
Run ./gradlew sonar
Generating dependency graph into '/runner/_work/Platsec-Gradle-Sample/Platsec-Gradle-Sample/dependency-graph-reports/platform_security_scan-build-1.json'
Resolving dependency graph plugin 1.3.0 from plugin repository: https://plugins.gradle.org/m2
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :compileTestJava NO-SOURCE

> Task :sonar
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/runner/.sonar/cache/ddd577cdcf31d738b1084c40c0f0843d/sonar-scanner-engine-shaded-9.9.0.65466-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/runner/.sonar/cache/c013475a936d69d09124614136e494e2/scanner-enterprise-9.9.0.65466-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Constructing renderer: org.gradle.github.dependencygraph.GitHubDependencyGraphRenderer

GitHubDependencyGraphRenderer: Wrote dependency snapshot to 
/runner/_work/Platsec-Gradle-Sample/Platsec-Gradle-Sample/dependency-graph-reports/platform_security_scan-build-1.json
```

I'm gonna try the other steps to see if that works

**Comment by bigdaz** [comment] 2024-04-30 06:18
Yes, that is odd. Again I think the best option is to save the generated dependency graph file to inspect. It could be that you have a firewall that is rejecting the submission because it is too large, or the file itself could be corrupted due to a problem with the plugin.

Attempting to submit the file directly (using `curl`) could provide more evidence.

**Comment by bigdaz** [comment] 2024-04-30 06:20
Note that the `sonar` execution should not be generating a dependency-graph file. This is caused by #204.

**Comment by glinero-king** [comment] 2024-05-21 07:16
Hey, just wanted to mention that I have been able to overcome the problem so far by following the previous advise:
- Making the dependency generation step independent from sonar, so we do not generate a dependency graph in that step.
- Using only the generation option
- Uploading the artifact in new step with the action/upload-artifact@v3

Thanks for the help!
